name: Android Build

on:
  push:
    branches:
      - main  # Veya kodunu yüklediğin dalın adı

jobs:
  build:
    runs-on: ubuntu-latest  # Derleme için Linux sunucusu kullanır

    steps:
    - uses: actions/checkout@v4  # Proje dosyalarını indir

    - name: Install Dependencies  # Buildozer ve temel paketleri kurar
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libssl-dev
        pip install buildozer cython

    - name: Accept Android SDK Licenses  # KIRMIZI HATAYI ÇÖZEN LİSANS KABULÜ
      run: yes | buildozer android update

    - name: Build Android APK  # APK'yı derle
      run: |
        buildozer android debug

    - name: Upload Artifact  # Oluşan APK'yı indirmek için kaydet
      uses: actions/upload-artifact@v4
      with:
        name: lo-app-apk
        path: bin/*.apk
        
