name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libssl-dev
        pip install buildozer cython

    # Bu adım, Buildozer'ın takılma ve lisans hatalarını çözer
    - name: Setup and Clean Buildozer Environment
      env:
        # Lisansları otomatik kabul et
        BUILD_ANDROID_SDK_ACCEPT_LICENSES: 1
        # Buildozer'a otomasyon ortamında çalıştığını söyler (Takılmayı çözer)
        CI: 1
      run: |
        buildozer clean
        buildozer android update

    - name: Build Android APK
      env:
        # Buildozer'a otomasyon ortamında çalıştığını söyler
        CI: 1
      run: buildozer android debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lo-app-apk
        path: bin/*.apk
        
